/**
 * E2E Test Runner — patcht .dev.vars auf lokales Supabase, startet Playwright,
 * stellt .dev.vars danach wieder her.
 *
 * Hintergrund: Playwright's globalSetup läuft NACH dem webServer-Start, aber
 * @astrojs/cloudflare liest .dev.vars in astro:config:done (Object.assign auf
 * process.env). Die Datei muss also vor dem Webserver-Start auf lokale Werte
 * gesetzt sein. Dieses Script übernimmt das als Wrapper um `playwright test`.
 */
import { existsSync, readFileSync, writeFileSync, copyFileSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const DEV_VARS = `${ROOT}/.dev.vars`;
const DEV_VARS_BAK = `${ROOT}/.dev.vars.e2e-bak`;
const ENV_E2E = `${ROOT}/.env.e2e`;

function parseEnvFile(path) {
  const out = {};
  if (!existsSync(path)) return out;
  for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

// 1. .dev.vars sichern und auf lokales Supabase patchen.
if (existsSync(DEV_VARS)) {
  copyFileSync(DEV_VARS, DEV_VARS_BAK);
}
const existing = parseEnvFile(DEV_VARS);
const e2eOverrides = parseEnvFile(ENV_E2E);
const merged = { ...existing, ...e2eOverrides };
const content =
  "# AUTO-GENERATED by scripts/e2e-runner.mjs — wird nach dem E2E-Lauf wiederhergestellt.\n" +
  Object.entries(merged)
    .map(([k, v]) => `${k}=${v}`)
    .join("\n") +
  "\n";
writeFileSync(DEV_VARS, content, "utf8");
console.log("[e2e-runner] .dev.vars → lokales Supabase (Original in .dev.vars.e2e-bak)");

// 2. Playwright starten (erbt alle Env-Vars des aktuellen Prozesses).
const result = spawnSync("npx", ["playwright", "test", ...process.argv.slice(2)], {
  stdio: "inherit",
  shell: true,
  env: process.env,
});

// 3. .dev.vars wiederherstellen (auch bei Fehler / Abbruch).
if (existsSync(DEV_VARS_BAK)) {
  copyFileSync(DEV_VARS_BAK, DEV_VARS);
  rmSync(DEV_VARS_BAK);
  console.log("[e2e-runner] .dev.vars wiederhergestellt.");
}

process.exit(result.status ?? 1);
